### PR TITLE
Add a BLS verification PPP

### PR DESCRIPTION
**Pull request by volcano-mash**

### CODE REVIEW

**Comment by AlistairStewart** [comment]
We should always do subgroup checks, especially for the signature. We'd want this to be useful on its own, without any other Arkworks support in the runtime.

The priority use case for this is Snowbridge which should be deployed soon.

**Comment by volcano-mash** [comment]
Sounds good. I've included the subgroup checks as discussed, and updated this PPP.

**Comment by burdges** [comment]
I'd expect https://github.com/w3f/PPPs/pull/8 supersedes this, especially once we get G_T arithmetic in there

**Comment by Noc2** [comment]
We will archive this repository in favor of the new [RFCs repository by the Fellowship](https://github.com/polkadot-fellows/RFCs). So, I'm closing the issue here. I recommend opening a PR at the new repository.

**Pull request closed without merging**
